version: '3.7'

services:
  mail-prod-api:
    container_name: mail-api
    restart: unless-stopped
    build:
      context: ./mail-server
      dockerfile: Dockerfile
    entrypoint: ["yarn", "start"]
    volumes:
      - ./mail-server:/mail-server
    expose:
      - '4000'
  static-app:
    container_name: mail-client-static
    build:
      context: ./mail-client
      dockerfile: Dockerfile
    links:
      - mail-prod-api
    depends_on:
      - mail-prod-api
    volumes:
      - ./mail-client:/mail-client
      - build:/mail-client/build

  reverse-proxy:
    container_name: mail-client-proxy
    restart: unless-stopped
    image: fholzer/nginx-brotli:latest
    links:
      - static-app
    depends_on:
      - static-app
    volumes:
      - build:/etc/nginx/html
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - '8001:80'
volumes:
  build:
