version: '3.7'

services:
  mail-prod-api:
    container_name: mail-prod-api
    build:
      context: ./mail-server
      dockerfile: Dockerfile
  mail-prod-static-app:
    container_name: mail-prod-static-app
    build:
      context: ./mail-client
      dockerfile: Dockerfile
    volumes:
      - build:/mail-client/build
  reverse-proxy:
    container_name: mail-client-proxy
    image: fholzer/nginx-brotli:latest
    links:
      - mail-prod-static-app
    depends_on:
      - mail-prod-static-app
    volumes:
      - build:/etc/nginx/html
      - ./nginx/default.nginx:/etc/nginx/conf.d/default.conf
    ports:
      - '8001:80'
volumes:
  build:
